// <auto-generated />
namespace Blood_Donation_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PopulatingGender_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulatingGender_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202010201443582_PopulatingGender_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
