// <auto-generated />
namespace Blood_Donation_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addingname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingname));
        
        string IMigrationMetadata.Id
        {
            get { return "202011190356186_addingname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
