// <auto-generated />
namespace Blood_Donation_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class populatingname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populatingname));
        
        string IMigrationMetadata.Id
        {
            get { return "202011190356490_populatingname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
